/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bond service. Represents a row in the &quot;fing_Bond&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fingence.slayer.model.impl.BondModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fingence.slayer.model.impl.BondImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see Bond
 * @see com.fingence.slayer.model.impl.BondImpl
 * @see com.fingence.slayer.model.impl.BondModelImpl
 * @generated
 */
public interface BondModel extends BaseModel<Bond> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bond model instance should use the {@link Bond} interface instead.
	 */

	/**
	 * Returns the primary key of this bond.
	 *
	 * @return the primary key of this bond
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bond.
	 *
	 * @param primaryKey the primary key of this bond
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset ID of this bond.
	 *
	 * @return the asset ID of this bond
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this bond.
	 *
	 * @param assetId the asset ID of this bond
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the issuer_bulk of this bond.
	 *
	 * @return the issuer_bulk of this bond
	 */
	@AutoEscape
	public String getIssuer_bulk();

	/**
	 * Sets the issuer_bulk of this bond.
	 *
	 * @param issuer_bulk the issuer_bulk of this bond
	 */
	public void setIssuer_bulk(String issuer_bulk);

	/**
	 * Returns the cpn of this bond.
	 *
	 * @return the cpn of this bond
	 */
	public double getCpn();

	/**
	 * Sets the cpn of this bond.
	 *
	 * @param cpn the cpn of this bond
	 */
	public void setCpn(double cpn);

	/**
	 * Returns the cpn_typ of this bond.
	 *
	 * @return the cpn_typ of this bond
	 */
	@AutoEscape
	public String getCpn_typ();

	/**
	 * Sets the cpn_typ of this bond.
	 *
	 * @param cpn_typ the cpn_typ of this bond
	 */
	public void setCpn_typ(String cpn_typ);

	/**
	 * Returns the mty_typ of this bond.
	 *
	 * @return the mty_typ of this bond
	 */
	@AutoEscape
	public String getMty_typ();

	/**
	 * Sets the mty_typ of this bond.
	 *
	 * @param mty_typ the mty_typ of this bond
	 */
	public void setMty_typ(String mty_typ);

	/**
	 * Returns the mty_years_tdy of this bond.
	 *
	 * @return the mty_years_tdy of this bond
	 */
	public double getMty_years_tdy();

	/**
	 * Sets the mty_years_tdy of this bond.
	 *
	 * @param mty_years_tdy the mty_years_tdy of this bond
	 */
	public void setMty_years_tdy(double mty_years_tdy);

	/**
	 * Returns the yld_ytm_ask of this bond.
	 *
	 * @return the yld_ytm_ask of this bond
	 */
	public double getYld_ytm_ask();

	/**
	 * Sets the yld_ytm_ask of this bond.
	 *
	 * @param yld_ytm_ask the yld_ytm_ask of this bond
	 */
	public void setYld_ytm_ask(double yld_ytm_ask);

	/**
	 * Returns the yld_ytm_bid of this bond.
	 *
	 * @return the yld_ytm_bid of this bond
	 */
	public double getYld_ytm_bid();

	/**
	 * Sets the yld_ytm_bid of this bond.
	 *
	 * @param yld_ytm_bid the yld_ytm_bid of this bond
	 */
	public void setYld_ytm_bid(double yld_ytm_bid);

	/**
	 * Returns the yld_cur_mid of this bond.
	 *
	 * @return the yld_cur_mid of this bond
	 */
	public double getYld_cur_mid();

	/**
	 * Sets the yld_cur_mid of this bond.
	 *
	 * @param yld_cur_mid the yld_cur_mid of this bond
	 */
	public void setYld_cur_mid(double yld_cur_mid);

	/**
	 * Returns the issue_dt of this bond.
	 *
	 * @return the issue_dt of this bond
	 */
	public Date getIssue_dt();

	/**
	 * Sets the issue_dt of this bond.
	 *
	 * @param issue_dt the issue_dt of this bond
	 */
	public void setIssue_dt(Date issue_dt);

	/**
	 * Returns the maturity_dt of this bond.
	 *
	 * @return the maturity_dt of this bond
	 */
	public Date getMaturity_dt();

	/**
	 * Sets the maturity_dt of this bond.
	 *
	 * @param maturity_dt the maturity_dt of this bond
	 */
	public void setMaturity_dt(Date maturity_dt);

	/**
	 * Returns the calc_typ of this bond.
	 *
	 * @return the calc_typ of this bond
	 */
	public double getCalc_typ();

	/**
	 * Sets the calc_typ of this bond.
	 *
	 * @param calc_typ the calc_typ of this bond
	 */
	public void setCalc_typ(double calc_typ);

	/**
	 * Returns the is_bond_no_calctyp of this bond.
	 *
	 * @return the is_bond_no_calctyp of this bond
	 */
	public boolean getIs_bond_no_calctyp();

	/**
	 * Returns <code>true</code> if this bond is is_bond_no_calctyp.
	 *
	 * @return <code>true</code> if this bond is is_bond_no_calctyp; <code>false</code> otherwise
	 */
	public boolean isIs_bond_no_calctyp();

	/**
	 * Sets whether this bond is is_bond_no_calctyp.
	 *
	 * @param is_bond_no_calctyp the is_bond_no_calctyp of this bond
	 */
	public void setIs_bond_no_calctyp(boolean is_bond_no_calctyp);

	/**
	 * Returns the collat_typ of this bond.
	 *
	 * @return the collat_typ of this bond
	 */
	@AutoEscape
	public String getCollat_typ();

	/**
	 * Sets the collat_typ of this bond.
	 *
	 * @param collat_typ the collat_typ of this bond
	 */
	public void setCollat_typ(String collat_typ);

	/**
	 * Returns the bb_composite of this bond.
	 *
	 * @return the bb_composite of this bond
	 */
	@AutoEscape
	public String getBb_composite();

	/**
	 * Sets the bb_composite of this bond.
	 *
	 * @param bb_composite the bb_composite of this bond
	 */
	public void setBb_composite(String bb_composite);

	/**
	 * Returns the rtg_sp of this bond.
	 *
	 * @return the rtg_sp of this bond
	 */
	@AutoEscape
	public String getRtg_sp();

	/**
	 * Sets the rtg_sp of this bond.
	 *
	 * @param rtg_sp the rtg_sp of this bond
	 */
	public void setRtg_sp(String rtg_sp);

	/**
	 * Returns the rtg_moody of this bond.
	 *
	 * @return the rtg_moody of this bond
	 */
	@AutoEscape
	public String getRtg_moody();

	/**
	 * Sets the rtg_moody of this bond.
	 *
	 * @param rtg_moody the rtg_moody of this bond
	 */
	public void setRtg_moody(String rtg_moody);

	/**
	 * Returns the rtg_fitch of this bond.
	 *
	 * @return the rtg_fitch of this bond
	 */
	@AutoEscape
	public String getRtg_fitch();

	/**
	 * Sets the rtg_fitch of this bond.
	 *
	 * @param rtg_fitch the rtg_fitch of this bond
	 */
	public void setRtg_fitch(String rtg_fitch);

	/**
	 * Returns the cpn_freq of this bond.
	 *
	 * @return the cpn_freq of this bond
	 */
	public double getCpn_freq();

	/**
	 * Sets the cpn_freq of this bond.
	 *
	 * @param cpn_freq the cpn_freq of this bond
	 */
	public void setCpn_freq(double cpn_freq);

	/**
	 * Returns the five_y_bid_cds_spread of this bond.
	 *
	 * @return the five_y_bid_cds_spread of this bond
	 */
	public double getFive_y_bid_cds_spread();

	/**
	 * Sets the five_y_bid_cds_spread of this bond.
	 *
	 * @param five_y_bid_cds_spread the five_y_bid_cds_spread of this bond
	 */
	public void setFive_y_bid_cds_spread(double five_y_bid_cds_spread);

	/**
	 * Returns the dur_mid of this bond.
	 *
	 * @return the dur_mid of this bond
	 */
	public double getDur_mid();

	/**
	 * Sets the dur_mid of this bond.
	 *
	 * @param dur_mid the dur_mid of this bond
	 */
	public void setDur_mid(double dur_mid);

	/**
	 * Returns the price_to_cash_flow of this bond.
	 *
	 * @return the price_to_cash_flow of this bond
	 */
	public double getPrice_to_cash_flow();

	/**
	 * Sets the price_to_cash_flow of this bond.
	 *
	 * @param price_to_cash_flow the price_to_cash_flow of this bond
	 */
	public void setPrice_to_cash_flow(double price_to_cash_flow);

	/**
	 * Returns the amount_issued of this bond.
	 *
	 * @return the amount_issued of this bond
	 */
	public double getAmount_issued();

	/**
	 * Sets the amount_issued of this bond.
	 *
	 * @param amount_issued the amount_issued of this bond
	 */
	public void setAmount_issued(double amount_issued);

	/**
	 * Returns the amount_outstanding of this bond.
	 *
	 * @return the amount_outstanding of this bond
	 */
	public double getAmount_outstanding();

	/**
	 * Sets the amount_outstanding of this bond.
	 *
	 * @param amount_outstanding the amount_outstanding of this bond
	 */
	public void setAmount_outstanding(double amount_outstanding);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Bond bond);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Bond> toCacheModel();

	@Override
	public Bond toEscapedModel();

	@Override
	public Bond toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}