/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Equity service. Represents a row in the &quot;fing_Equity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fingence.slayer.model.impl.EquityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fingence.slayer.model.impl.EquityImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see Equity
 * @see com.fingence.slayer.model.impl.EquityImpl
 * @see com.fingence.slayer.model.impl.EquityModelImpl
 * @generated
 */
public interface EquityModel extends BaseModel<Equity> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a equity model instance should use the {@link Equity} interface instead.
	 */

	/**
	 * Returns the primary key of this equity.
	 *
	 * @return the primary key of this equity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this equity.
	 *
	 * @param primaryKey the primary key of this equity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the asset ID of this equity.
	 *
	 * @return the asset ID of this equity
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this equity.
	 *
	 * @param assetId the asset ID of this equity
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the eqy_alpha of this equity.
	 *
	 * @return the eqy_alpha of this equity
	 */
	public double getEqy_alpha();

	/**
	 * Sets the eqy_alpha of this equity.
	 *
	 * @param eqy_alpha the eqy_alpha of this equity
	 */
	public void setEqy_alpha(double eqy_alpha);

	/**
	 * Returns the dividend_yield of this equity.
	 *
	 * @return the dividend_yield of this equity
	 */
	public double getDividend_yield();

	/**
	 * Sets the dividend_yield of this equity.
	 *
	 * @param dividend_yield the dividend_yield of this equity
	 */
	public void setDividend_yield(double dividend_yield);

	/**
	 * Returns the eqy_dvd_yld_12m of this equity.
	 *
	 * @return the eqy_dvd_yld_12m of this equity
	 */
	public double getEqy_dvd_yld_12m();

	/**
	 * Sets the eqy_dvd_yld_12m of this equity.
	 *
	 * @param eqy_dvd_yld_12m the eqy_dvd_yld_12m of this equity
	 */
	public void setEqy_dvd_yld_12m(double eqy_dvd_yld_12m);

	/**
	 * Returns the eqy_dvd_yld_es of this equity.
	 *
	 * @return the eqy_dvd_yld_es of this equity
	 */
	public double getEqy_dvd_yld_es();

	/**
	 * Sets the eqy_dvd_yld_es of this equity.
	 *
	 * @param eqy_dvd_yld_es the eqy_dvd_yld_es of this equity
	 */
	public void setEqy_dvd_yld_es(double eqy_dvd_yld_es);

	/**
	 * Returns the dvd_payout_ratio of this equity.
	 *
	 * @return the dvd_payout_ratio of this equity
	 */
	public double getDvd_payout_ratio();

	/**
	 * Sets the dvd_payout_ratio of this equity.
	 *
	 * @param dvd_payout_ratio the dvd_payout_ratio of this equity
	 */
	public void setDvd_payout_ratio(double dvd_payout_ratio);

	/**
	 * Returns the pe_ratio of this equity.
	 *
	 * @return the pe_ratio of this equity
	 */
	public double getPe_ratio();

	/**
	 * Sets the pe_ratio of this equity.
	 *
	 * @param pe_ratio the pe_ratio of this equity
	 */
	public void setPe_ratio(double pe_ratio);

	/**
	 * Returns the tot_debt_to_com_eqy of this equity.
	 *
	 * @return the tot_debt_to_com_eqy of this equity
	 */
	public double getTot_debt_to_com_eqy();

	/**
	 * Sets the tot_debt_to_com_eqy of this equity.
	 *
	 * @param tot_debt_to_com_eqy the tot_debt_to_com_eqy of this equity
	 */
	public void setTot_debt_to_com_eqy(double tot_debt_to_com_eqy);

	/**
	 * Returns the ebitda_to_revenue of this equity.
	 *
	 * @return the ebitda_to_revenue of this equity
	 */
	public double getEbitda_to_revenue();

	/**
	 * Sets the ebitda_to_revenue of this equity.
	 *
	 * @param ebitda_to_revenue the ebitda_to_revenue of this equity
	 */
	public void setEbitda_to_revenue(double ebitda_to_revenue);

	/**
	 * Returns the trail_12m_prof_margin of this equity.
	 *
	 * @return the trail_12m_prof_margin of this equity
	 */
	public double getTrail_12m_prof_margin();

	/**
	 * Sets the trail_12m_prof_margin of this equity.
	 *
	 * @param trail_12m_prof_margin the trail_12m_prof_margin of this equity
	 */
	public void setTrail_12m_prof_margin(double trail_12m_prof_margin);

	/**
	 * Returns the best_current_ev_best_opp of this equity.
	 *
	 * @return the best_current_ev_best_opp of this equity
	 */
	public double getBest_current_ev_best_opp();

	/**
	 * Sets the best_current_ev_best_opp of this equity.
	 *
	 * @param best_current_ev_best_opp the best_current_ev_best_opp of this equity
	 */
	public void setBest_current_ev_best_opp(double best_current_ev_best_opp);

	/**
	 * Returns the eqy_beta of this equity.
	 *
	 * @return the eqy_beta of this equity
	 */
	public double getEqy_beta();

	/**
	 * Sets the eqy_beta of this equity.
	 *
	 * @param eqy_beta the eqy_beta of this equity
	 */
	public void setEqy_beta(double eqy_beta);

	/**
	 * Returns the return_sharpe_ratio of this equity.
	 *
	 * @return the return_sharpe_ratio of this equity
	 */
	public double getReturn_sharpe_ratio();

	/**
	 * Sets the return_sharpe_ratio of this equity.
	 *
	 * @param return_sharpe_ratio the return_sharpe_ratio of this equity
	 */
	public void setReturn_sharpe_ratio(double return_sharpe_ratio);

	/**
	 * Returns the eqy_sharpe_ratio_1yr of this equity.
	 *
	 * @return the eqy_sharpe_ratio_1yr of this equity
	 */
	public double getEqy_sharpe_ratio_1yr();

	/**
	 * Sets the eqy_sharpe_ratio_1yr of this equity.
	 *
	 * @param eqy_sharpe_ratio_1yr the eqy_sharpe_ratio_1yr of this equity
	 */
	public void setEqy_sharpe_ratio_1yr(double eqy_sharpe_ratio_1yr);

	/**
	 * Returns the eqy_sharpe_ratio_3yr of this equity.
	 *
	 * @return the eqy_sharpe_ratio_3yr of this equity
	 */
	public double getEqy_sharpe_ratio_3yr();

	/**
	 * Sets the eqy_sharpe_ratio_3yr of this equity.
	 *
	 * @param eqy_sharpe_ratio_3yr the eqy_sharpe_ratio_3yr of this equity
	 */
	public void setEqy_sharpe_ratio_3yr(double eqy_sharpe_ratio_3yr);

	/**
	 * Returns the eqy_sharpe_ratio_5yr of this equity.
	 *
	 * @return the eqy_sharpe_ratio_5yr of this equity
	 */
	public double getEqy_sharpe_ratio_5yr();

	/**
	 * Sets the eqy_sharpe_ratio_5yr of this equity.
	 *
	 * @param eqy_sharpe_ratio_5yr the eqy_sharpe_ratio_5yr of this equity
	 */
	public void setEqy_sharpe_ratio_5yr(double eqy_sharpe_ratio_5yr);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Equity equity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Equity> toCacheModel();

	@Override
	public Equity toEscapedModel();

	@Override
	public Equity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}