/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the History service. Represents a row in the &quot;fing_History&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fingence.slayer.model.impl.HistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fingence.slayer.model.impl.HistoryImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see History
 * @see com.fingence.slayer.model.impl.HistoryImpl
 * @see com.fingence.slayer.model.impl.HistoryModelImpl
 * @generated
 */
public interface HistoryModel extends BaseModel<History> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a history model instance should use the {@link History} interface instead.
	 */

	/**
	 * Returns the primary key of this history.
	 *
	 * @return the primary key of this history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this history.
	 *
	 * @param primaryKey the primary key of this history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rec ID of this history.
	 *
	 * @return the rec ID of this history
	 */
	public long getRecId();

	/**
	 * Sets the rec ID of this history.
	 *
	 * @param recId the rec ID of this history
	 */
	public void setRecId(long recId);

	/**
	 * Returns the asset ID of this history.
	 *
	 * @return the asset ID of this history
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this history.
	 *
	 * @param assetId the asset ID of this history
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the log date of this history.
	 *
	 * @return the log date of this history
	 */
	public Date getLogDate();

	/**
	 * Sets the log date of this history.
	 *
	 * @param logDate the log date of this history
	 */
	public void setLogDate(Date logDate);

	/**
	 * Returns the value of this history.
	 *
	 * @return the value of this history
	 */
	public double getValue();

	/**
	 * Sets the value of this history.
	 *
	 * @param value the value of this history
	 */
	public void setValue(double value);

	/**
	 * Returns the type of this history.
	 *
	 * @return the type of this history
	 */
	public int getType();

	/**
	 * Sets the type of this history.
	 *
	 * @param type the type of this history
	 */
	public void setType(int type);

	/**
	 * Returns the principal of this history.
	 *
	 * @return the principal of this history
	 */
	public double getPrincipal();

	/**
	 * Sets the principal of this history.
	 *
	 * @param principal the principal of this history
	 */
	public void setPrincipal(double principal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(History history);

	@Override
	public int hashCode();

	@Override
	public CacheModel<History> toCacheModel();

	@Override
	public History toEscapedModel();

	@Override
	public History toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}