/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MyResult service. Represents a row in the &quot;fing_MyResult&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fingence.slayer.model.impl.MyResultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fingence.slayer.model.impl.MyResultImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see MyResult
 * @see com.fingence.slayer.model.impl.MyResultImpl
 * @see com.fingence.slayer.model.impl.MyResultModelImpl
 * @generated
 */
public interface MyResultModel extends BaseModel<MyResult> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my result model instance should use the {@link MyResult} interface instead.
	 */

	/**
	 * Returns the primary key of this my result.
	 *
	 * @return the primary key of this my result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my result.
	 *
	 * @param primaryKey the primary key of this my result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item ID of this my result.
	 *
	 * @return the item ID of this my result
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this my result.
	 *
	 * @param itemId the item ID of this my result
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the portfolio ID of this my result.
	 *
	 * @return the portfolio ID of this my result
	 */
	public long getPortfolioId();

	/**
	 * Sets the portfolio ID of this my result.
	 *
	 * @param portfolioId the portfolio ID of this my result
	 */
	public void setPortfolioId(long portfolioId);

	/**
	 * Returns the institution of this my result.
	 *
	 * @return the institution of this my result
	 */
	@AutoEscape
	public String getInstitution();

	/**
	 * Sets the institution of this my result.
	 *
	 * @param institution the institution of this my result
	 */
	public void setInstitution(String institution);

	/**
	 * Returns the asset ID of this my result.
	 *
	 * @return the asset ID of this my result
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this my result.
	 *
	 * @param assetId the asset ID of this my result
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the security_ticker of this my result.
	 *
	 * @return the security_ticker of this my result
	 */
	@AutoEscape
	public String getSecurity_ticker();

	/**
	 * Sets the security_ticker of this my result.
	 *
	 * @param security_ticker the security_ticker of this my result
	 */
	public void setSecurity_ticker(String security_ticker);

	/**
	 * Returns the id_isin of this my result.
	 *
	 * @return the id_isin of this my result
	 */
	@AutoEscape
	public String getId_isin();

	/**
	 * Sets the id_isin of this my result.
	 *
	 * @param id_isin the id_isin of this my result
	 */
	public void setId_isin(String id_isin);

	/**
	 * Returns the name of this my result.
	 *
	 * @return the name of this my result
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this my result.
	 *
	 * @param name the name of this my result
	 */
	public void setName(String name);

	/**
	 * Returns the industry_sector of this my result.
	 *
	 * @return the industry_sector of this my result
	 */
	@AutoEscape
	public String getIndustry_sector();

	/**
	 * Sets the industry_sector of this my result.
	 *
	 * @param industry_sector the industry_sector of this my result
	 */
	public void setIndustry_sector(String industry_sector);

	/**
	 * Returns the purchase qty of this my result.
	 *
	 * @return the purchase qty of this my result
	 */
	public double getPurchaseQty();

	/**
	 * Sets the purchase qty of this my result.
	 *
	 * @param purchaseQty the purchase qty of this my result
	 */
	public void setPurchaseQty(double purchaseQty);

	/**
	 * Returns the purchase date of this my result.
	 *
	 * @return the purchase date of this my result
	 */
	public Date getPurchaseDate();

	/**
	 * Sets the purchase date of this my result.
	 *
	 * @param purchaseDate the purchase date of this my result
	 */
	public void setPurchaseDate(Date purchaseDate);

	/**
	 * Returns the current_price of this my result.
	 *
	 * @return the current_price of this my result
	 */
	public double getCurrent_price();

	/**
	 * Sets the current_price of this my result.
	 *
	 * @param current_price the current_price of this my result
	 */
	public void setCurrent_price(double current_price);

	/**
	 * Returns the purchased fx of this my result.
	 *
	 * @return the purchased fx of this my result
	 */
	public double getPurchasedFx();

	/**
	 * Sets the purchased fx of this my result.
	 *
	 * @param purchasedFx the purchased fx of this my result
	 */
	public void setPurchasedFx(double purchasedFx);

	/**
	 * Returns the current_fx of this my result.
	 *
	 * @return the current_fx of this my result
	 */
	public double getCurrent_fx();

	/**
	 * Sets the current_fx of this my result.
	 *
	 * @param current_fx the current_fx of this my result
	 */
	public void setCurrent_fx(double current_fx);

	/**
	 * Returns the base currency of this my result.
	 *
	 * @return the base currency of this my result
	 */
	@AutoEscape
	public String getBaseCurrency();

	/**
	 * Sets the base currency of this my result.
	 *
	 * @param baseCurrency the base currency of this my result
	 */
	public void setBaseCurrency(String baseCurrency);

	/**
	 * Returns the security_des of this my result.
	 *
	 * @return the security_des of this my result
	 */
	@AutoEscape
	public String getSecurity_des();

	/**
	 * Sets the security_des of this my result.
	 *
	 * @param security_des the security_des of this my result
	 */
	public void setSecurity_des(String security_des);

	/**
	 * Returns the security_class_int of this my result.
	 *
	 * @return the security_class_int of this my result
	 */
	public int getSecurity_class_int();

	/**
	 * Sets the security_class_int of this my result.
	 *
	 * @param security_class_int the security_class_int of this my result
	 */
	public void setSecurity_class_int(int security_class_int);

	/**
	 * Returns the security_class of this my result.
	 *
	 * @return the security_class of this my result
	 */
	@AutoEscape
	public String getSecurity_class();

	/**
	 * Sets the security_class of this my result.
	 *
	 * @param security_class the security_class of this my result
	 */
	public void setSecurity_class(String security_class);

	/**
	 * Returns the security_typ of this my result.
	 *
	 * @return the security_typ of this my result
	 */
	@AutoEscape
	public String getSecurity_typ();

	/**
	 * Sets the security_typ of this my result.
	 *
	 * @param security_typ the security_typ of this my result
	 */
	public void setSecurity_typ(String security_typ);

	/**
	 * Returns the security_typ2 of this my result.
	 *
	 * @return the security_typ2 of this my result
	 */
	@AutoEscape
	public String getSecurity_typ2();

	/**
	 * Sets the security_typ2 of this my result.
	 *
	 * @param security_typ2 the security_typ2 of this my result
	 */
	public void setSecurity_typ2(String security_typ2);

	/**
	 * Returns the asset_class of this my result.
	 *
	 * @return the asset_class of this my result
	 */
	@AutoEscape
	public String getAsset_class();

	/**
	 * Sets the asset_class of this my result.
	 *
	 * @param asset_class the asset_class of this my result
	 */
	public void setAsset_class(String asset_class);

	/**
	 * Returns the asset_sub_class of this my result.
	 *
	 * @return the asset_sub_class of this my result
	 */
	@AutoEscape
	public String getAsset_sub_class();

	/**
	 * Sets the asset_sub_class of this my result.
	 *
	 * @param asset_sub_class the asset_sub_class of this my result
	 */
	public void setAsset_sub_class(String asset_sub_class);

	/**
	 * Returns the parent_comp_name of this my result.
	 *
	 * @return the parent_comp_name of this my result
	 */
	@AutoEscape
	public String getParent_comp_name();

	/**
	 * Sets the parent_comp_name of this my result.
	 *
	 * @param parent_comp_name the parent_comp_name of this my result
	 */
	public void setParent_comp_name(String parent_comp_name);

	/**
	 * Returns the country ID of this my result.
	 *
	 * @return the country ID of this my result
	 */
	public long getCountryId();

	/**
	 * Sets the country ID of this my result.
	 *
	 * @param countryId the country ID of this my result
	 */
	public void setCountryId(long countryId);

	/**
	 * Returns the country name of this my result.
	 *
	 * @return the country name of this my result
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this my result.
	 *
	 * @param countryName the country name of this my result
	 */
	public void setCountryName(String countryName);

	/**
	 * Returns the country of risk of this my result.
	 *
	 * @return the country of risk of this my result
	 */
	public long getCountryOfRisk();

	/**
	 * Sets the country of risk of this my result.
	 *
	 * @param countryOfRisk the country of risk of this my result
	 */
	public void setCountryOfRisk(long countryOfRisk);

	/**
	 * Returns the country of risk name of this my result.
	 *
	 * @return the country of risk name of this my result
	 */
	@AutoEscape
	public String getCountryOfRiskName();

	/**
	 * Sets the country of risk name of this my result.
	 *
	 * @param countryOfRiskName the country of risk name of this my result
	 */
	public void setCountryOfRiskName(String countryOfRiskName);

	/**
	 * Returns the currency_ of this my result.
	 *
	 * @return the currency_ of this my result
	 */
	@AutoEscape
	public String getCurrency_();

	/**
	 * Sets the currency_ of this my result.
	 *
	 * @param currency_ the currency_ of this my result
	 */
	public void setCurrency_(String currency_);

	/**
	 * Returns the currency desc of this my result.
	 *
	 * @return the currency desc of this my result
	 */
	@AutoEscape
	public String getCurrencyDesc();

	/**
	 * Sets the currency desc of this my result.
	 *
	 * @param currencyDesc the currency desc of this my result
	 */
	public void setCurrencyDesc(String currencyDesc);

	/**
	 * Returns the purchased market value of this my result.
	 *
	 * @return the purchased market value of this my result
	 */
	public double getPurchasedMarketValue();

	/**
	 * Sets the purchased market value of this my result.
	 *
	 * @param purchasedMarketValue the purchased market value of this my result
	 */
	public void setPurchasedMarketValue(double purchasedMarketValue);

	/**
	 * Returns the current market value of this my result.
	 *
	 * @return the current market value of this my result
	 */
	public double getCurrentMarketValue();

	/**
	 * Sets the current market value of this my result.
	 *
	 * @param currentMarketValue the current market value of this my result
	 */
	public void setCurrentMarketValue(double currentMarketValue);

	/**
	 * Returns the gain_loss of this my result.
	 *
	 * @return the gain_loss of this my result
	 */
	public double getGain_loss();

	/**
	 * Sets the gain_loss of this my result.
	 *
	 * @param gain_loss the gain_loss of this my result
	 */
	public void setGain_loss(double gain_loss);

	/**
	 * Returns the gain_loss_percent of this my result.
	 *
	 * @return the gain_loss_percent of this my result
	 */
	public double getGain_loss_percent();

	/**
	 * Sets the gain_loss_percent of this my result.
	 *
	 * @param gain_loss_percent the gain_loss_percent of this my result
	 */
	public void setGain_loss_percent(double gain_loss_percent);

	/**
	 * Returns the fx_gain_loss of this my result.
	 *
	 * @return the fx_gain_loss of this my result
	 */
	public double getFx_gain_loss();

	/**
	 * Sets the fx_gain_loss of this my result.
	 *
	 * @param fx_gain_loss the fx_gain_loss of this my result
	 */
	public void setFx_gain_loss(double fx_gain_loss);

	/**
	 * Returns the income of this my result.
	 *
	 * @return the income of this my result
	 */
	public double getIncome();

	/**
	 * Sets the income of this my result.
	 *
	 * @param income the income of this my result
	 */
	public void setIncome(double income);

	/**
	 * Returns the currency symbol of this my result.
	 *
	 * @return the currency symbol of this my result
	 */
	@AutoEscape
	public String getCurrencySymbol();

	/**
	 * Sets the currency symbol of this my result.
	 *
	 * @param currencySymbol the currency symbol of this my result
	 */
	public void setCurrencySymbol(String currencySymbol);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MyResult myResult);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MyResult> toCacheModel();

	@Override
	public MyResult toEscapedModel();

	@Override
	public MyResult toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}