/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Rating service. Represents a row in the &quot;fing_Rating&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fingence.slayer.model.impl.RatingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fingence.slayer.model.impl.RatingImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see Rating
 * @see com.fingence.slayer.model.impl.RatingImpl
 * @see com.fingence.slayer.model.impl.RatingModelImpl
 * @generated
 */
public interface RatingModel extends BaseModel<Rating> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rating model instance should use the {@link Rating} interface instead.
	 */

	/**
	 * Returns the primary key of this rating.
	 *
	 * @return the primary key of this rating
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rating.
	 *
	 * @param primaryKey the primary key of this rating
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rating ID of this rating.
	 *
	 * @return the rating ID of this rating
	 */
	public long getRatingId();

	/**
	 * Sets the rating ID of this rating.
	 *
	 * @param ratingId the rating ID of this rating
	 */
	public void setRatingId(long ratingId);

	/**
	 * Returns the moodys of this rating.
	 *
	 * @return the moodys of this rating
	 */
	@AutoEscape
	public String getMoodys();

	/**
	 * Sets the moodys of this rating.
	 *
	 * @param moodys the moodys of this rating
	 */
	public void setMoodys(String moodys);

	/**
	 * Returns the sandp of this rating.
	 *
	 * @return the sandp of this rating
	 */
	@AutoEscape
	public String getSandp();

	/**
	 * Sets the sandp of this rating.
	 *
	 * @param sandp the sandp of this rating
	 */
	public void setSandp(String sandp);

	/**
	 * Returns the fitch of this rating.
	 *
	 * @return the fitch of this rating
	 */
	@AutoEscape
	public String getFitch();

	/**
	 * Sets the fitch of this rating.
	 *
	 * @param fitch the fitch of this rating
	 */
	public void setFitch(String fitch);

	/**
	 * Returns the general of this rating.
	 *
	 * @return the general of this rating
	 */
	@AutoEscape
	public String getGeneral();

	/**
	 * Sets the general of this rating.
	 *
	 * @param general the general of this rating
	 */
	public void setGeneral(String general);

	/**
	 * Returns the description of this rating.
	 *
	 * @return the description of this rating
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this rating.
	 *
	 * @param description the description of this rating
	 */
	public void setDescription(String description);

	/**
	 * Returns the credit worthiness of this rating.
	 *
	 * @return the credit worthiness of this rating
	 */
	@AutoEscape
	public String getCreditWorthiness();

	/**
	 * Sets the credit worthiness of this rating.
	 *
	 * @param creditWorthiness the credit worthiness of this rating
	 */
	public void setCreditWorthiness(String creditWorthiness);

	/**
	 * Returns the category of this rating.
	 *
	 * @return the category of this rating
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this rating.
	 *
	 * @param category the category of this rating
	 */
	public void setCategory(String category);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Rating rating);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Rating> toCacheModel();

	@Override
	public Rating toEscapedModel();

	@Override
	public Rating toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}