/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model;

import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ReportConfig service. Represents a row in the &quot;fing_ReportConfig&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fingence.slayer.model.impl.ReportConfigModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fingence.slayer.model.impl.ReportConfigImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see ReportConfig
 * @see com.fingence.slayer.model.impl.ReportConfigImpl
 * @see com.fingence.slayer.model.impl.ReportConfigModelImpl
 * @generated
 */
public interface ReportConfigModel extends AttachedModel, BaseModel<ReportConfig> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a report config model instance should use the {@link ReportConfig} interface instead.
	 */

	/**
	 * Returns the primary key of this report config.
	 *
	 * @return the primary key of this report config
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this report config.
	 *
	 * @param primaryKey the primary key of this report config
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rec ID of this report config.
	 *
	 * @return the rec ID of this report config
	 */
	public long getRecId();

	/**
	 * Sets the rec ID of this report config.
	 *
	 * @param recId the rec ID of this report config
	 */
	public void setRecId(long recId);

	/**
	 * Returns the report ID of this report config.
	 *
	 * @return the report ID of this report config
	 */
	public long getReportId();

	/**
	 * Sets the report ID of this report config.
	 *
	 * @param reportId the report ID of this report config
	 */
	public void setReportId(long reportId);

	/**
	 * Returns the enabled of this report config.
	 *
	 * @return the enabled of this report config
	 */
	public boolean getEnabled();

	/**
	 * Returns <code>true</code> if this report config is enabled.
	 *
	 * @return <code>true</code> if this report config is enabled; <code>false</code> otherwise
	 */
	public boolean isEnabled();

	/**
	 * Sets whether this report config is enabled.
	 *
	 * @param enabled the enabled of this report config
	 */
	public void setEnabled(boolean enabled);

	/**
	 * Returns the class p k of this report config.
	 *
	 * @return the class p k of this report config
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this report config.
	 *
	 * @param classPK the class p k of this report config
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the fully qualified class name of this report config.
	 *
	 * @return the fully qualified class name of this report config
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this report config.
	 *
	 * @return the class name ID of this report config
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this report config.
	 *
	 * @param classNameId the class name ID of this report config
	 */
	@Override
	public void setClassNameId(long classNameId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ReportConfig reportConfig);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ReportConfig> toCacheModel();

	@Override
	public ReportConfig toEscapedModel();

	@Override
	public ReportConfig toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}