/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model.impl;

import com.fingence.slayer.model.Asset;
import com.fingence.slayer.model.AssetModel;
import com.fingence.slayer.model.AssetSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Asset service. Represents a row in the &quot;fing_Asset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fingence.slayer.model.AssetModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see AssetImpl
 * @see com.fingence.slayer.model.Asset
 * @see com.fingence.slayer.model.AssetModel
 * @generated
 */
@JSON(strict = true)
public class AssetModelImpl extends BaseModelImpl<Asset> implements AssetModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset model instance should use the {@link com.fingence.slayer.model.Asset} interface instead.
	 */
	public static final String TABLE_NAME = "fing_Asset";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assetId", Types.BIGINT },
			{ "security_ticker", Types.VARCHAR },
			{ "id_cusip", Types.VARCHAR },
			{ "id_isin", Types.VARCHAR },
			{ "id_bb_global", Types.VARCHAR },
			{ "id_bb_sec_num_src", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "chg_pct_mtd", Types.DOUBLE },
			{ "chg_pct_5d", Types.DOUBLE },
			{ "chg_pct_1m", Types.DOUBLE },
			{ "chg_pct_3m", Types.DOUBLE },
			{ "chg_pct_6m", Types.DOUBLE },
			{ "chg_pct_ytd", Types.DOUBLE },
			{ "chg_pct_high_52week", Types.DOUBLE },
			{ "chg_pct_low_52week", Types.DOUBLE },
			{ "chg_pct_1yr", Types.DOUBLE },
			{ "chg_trr_5yr", Types.DOUBLE },
			{ "current_price", Types.DOUBLE },
			{ "last_price", Types.DOUBLE },
			{ "bid_price", Types.DOUBLE },
			{ "ask_price", Types.DOUBLE },
			{ "security_des", Types.VARCHAR },
			{ "parent_comp_name", Types.VARCHAR },
			{ "security_class", Types.INTEGER },
			{ "volatility_30d", Types.DOUBLE },
			{ "volatility_90d", Types.DOUBLE },
			{ "volatility_180d", Types.DOUBLE },
			{ "volatility_360d", Types.DOUBLE },
			{ "currency_", Types.VARCHAR },
			{ "country", Types.BIGINT },
			{ "country_of_risk", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table fing_Asset (assetId LONG not null primary key,security_ticker VARCHAR(75) null,id_cusip VARCHAR(75) null,id_isin VARCHAR(75) null,id_bb_global VARCHAR(75) null,id_bb_sec_num_src LONG,name VARCHAR(75) null,chg_pct_mtd DOUBLE,chg_pct_5d DOUBLE,chg_pct_1m DOUBLE,chg_pct_3m DOUBLE,chg_pct_6m DOUBLE,chg_pct_ytd DOUBLE,chg_pct_high_52week DOUBLE,chg_pct_low_52week DOUBLE,chg_pct_1yr DOUBLE,chg_trr_5yr DOUBLE,current_price DOUBLE,last_price DOUBLE,bid_price DOUBLE,ask_price DOUBLE,security_des VARCHAR(75) null,parent_comp_name VARCHAR(75) null,security_class INTEGER,volatility_30d DOUBLE,volatility_90d DOUBLE,volatility_180d DOUBLE,volatility_360d DOUBLE,currency_ VARCHAR(75) null,country LONG,country_of_risk LONG,createDate DATE null,modifiedDate DATE null,companyId LONG,userId LONG,userName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table fing_Asset";
	public static final String ORDER_BY_JPQL = " ORDER BY asset.assetId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY fing_Asset.assetId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fingence.slayer.model.Asset"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fingence.slayer.model.Asset"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.fingence.slayer.model.Asset"),
			true);
	public static long ID_ISIN_COLUMN_BITMASK = 1L;
	public static long SECURITY_TICKER_COLUMN_BITMASK = 2L;
	public static long ASSETID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Asset toModel(AssetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Asset model = new AssetImpl();

		model.setAssetId(soapModel.getAssetId());
		model.setSecurity_ticker(soapModel.getSecurity_ticker());
		model.setId_cusip(soapModel.getId_cusip());
		model.setId_isin(soapModel.getId_isin());
		model.setId_bb_global(soapModel.getId_bb_global());
		model.setId_bb_sec_num_src(soapModel.getId_bb_sec_num_src());
		model.setName(soapModel.getName());
		model.setChg_pct_mtd(soapModel.getChg_pct_mtd());
		model.setChg_pct_5d(soapModel.getChg_pct_5d());
		model.setChg_pct_1m(soapModel.getChg_pct_1m());
		model.setChg_pct_3m(soapModel.getChg_pct_3m());
		model.setChg_pct_6m(soapModel.getChg_pct_6m());
		model.setChg_pct_ytd(soapModel.getChg_pct_ytd());
		model.setChg_pct_high_52week(soapModel.getChg_pct_high_52week());
		model.setChg_pct_low_52week(soapModel.getChg_pct_low_52week());
		model.setChg_pct_1yr(soapModel.getChg_pct_1yr());
		model.setChg_trr_5yr(soapModel.getChg_trr_5yr());
		model.setCurrent_price(soapModel.getCurrent_price());
		model.setLast_price(soapModel.getLast_price());
		model.setBid_price(soapModel.getBid_price());
		model.setAsk_price(soapModel.getAsk_price());
		model.setSecurity_des(soapModel.getSecurity_des());
		model.setParent_comp_name(soapModel.getParent_comp_name());
		model.setSecurity_class(soapModel.getSecurity_class());
		model.setVolatility_30d(soapModel.getVolatility_30d());
		model.setVolatility_90d(soapModel.getVolatility_90d());
		model.setVolatility_180d(soapModel.getVolatility_180d());
		model.setVolatility_360d(soapModel.getVolatility_360d());
		model.setCurrency(soapModel.getCurrency());
		model.setCountry(soapModel.getCountry());
		model.setCountry_of_risk(soapModel.getCountry_of_risk());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Asset> toModels(AssetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Asset> models = new ArrayList<Asset>(soapModels.length);

		for (AssetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fingence.slayer.model.Asset"));

	public AssetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Asset.class;
	}

	@Override
	public String getModelClassName() {
		return Asset.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assetId", getAssetId());
		attributes.put("security_ticker", getSecurity_ticker());
		attributes.put("id_cusip", getId_cusip());
		attributes.put("id_isin", getId_isin());
		attributes.put("id_bb_global", getId_bb_global());
		attributes.put("id_bb_sec_num_src", getId_bb_sec_num_src());
		attributes.put("name", getName());
		attributes.put("chg_pct_mtd", getChg_pct_mtd());
		attributes.put("chg_pct_5d", getChg_pct_5d());
		attributes.put("chg_pct_1m", getChg_pct_1m());
		attributes.put("chg_pct_3m", getChg_pct_3m());
		attributes.put("chg_pct_6m", getChg_pct_6m());
		attributes.put("chg_pct_ytd", getChg_pct_ytd());
		attributes.put("chg_pct_high_52week", getChg_pct_high_52week());
		attributes.put("chg_pct_low_52week", getChg_pct_low_52week());
		attributes.put("chg_pct_1yr", getChg_pct_1yr());
		attributes.put("chg_trr_5yr", getChg_trr_5yr());
		attributes.put("current_price", getCurrent_price());
		attributes.put("last_price", getLast_price());
		attributes.put("bid_price", getBid_price());
		attributes.put("ask_price", getAsk_price());
		attributes.put("security_des", getSecurity_des());
		attributes.put("parent_comp_name", getParent_comp_name());
		attributes.put("security_class", getSecurity_class());
		attributes.put("volatility_30d", getVolatility_30d());
		attributes.put("volatility_90d", getVolatility_90d());
		attributes.put("volatility_180d", getVolatility_180d());
		attributes.put("volatility_360d", getVolatility_360d());
		attributes.put("currency", getCurrency());
		attributes.put("country", getCountry());
		attributes.put("country_of_risk", getCountry_of_risk());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assetId = (Long)attributes.get("assetId");

		if (assetId != null) {
			setAssetId(assetId);
		}

		String security_ticker = (String)attributes.get("security_ticker");

		if (security_ticker != null) {
			setSecurity_ticker(security_ticker);
		}

		String id_cusip = (String)attributes.get("id_cusip");

		if (id_cusip != null) {
			setId_cusip(id_cusip);
		}

		String id_isin = (String)attributes.get("id_isin");

		if (id_isin != null) {
			setId_isin(id_isin);
		}

		String id_bb_global = (String)attributes.get("id_bb_global");

		if (id_bb_global != null) {
			setId_bb_global(id_bb_global);
		}

		Long id_bb_sec_num_src = (Long)attributes.get("id_bb_sec_num_src");

		if (id_bb_sec_num_src != null) {
			setId_bb_sec_num_src(id_bb_sec_num_src);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Double chg_pct_mtd = (Double)attributes.get("chg_pct_mtd");

		if (chg_pct_mtd != null) {
			setChg_pct_mtd(chg_pct_mtd);
		}

		Double chg_pct_5d = (Double)attributes.get("chg_pct_5d");

		if (chg_pct_5d != null) {
			setChg_pct_5d(chg_pct_5d);
		}

		Double chg_pct_1m = (Double)attributes.get("chg_pct_1m");

		if (chg_pct_1m != null) {
			setChg_pct_1m(chg_pct_1m);
		}

		Double chg_pct_3m = (Double)attributes.get("chg_pct_3m");

		if (chg_pct_3m != null) {
			setChg_pct_3m(chg_pct_3m);
		}

		Double chg_pct_6m = (Double)attributes.get("chg_pct_6m");

		if (chg_pct_6m != null) {
			setChg_pct_6m(chg_pct_6m);
		}

		Double chg_pct_ytd = (Double)attributes.get("chg_pct_ytd");

		if (chg_pct_ytd != null) {
			setChg_pct_ytd(chg_pct_ytd);
		}

		Double chg_pct_high_52week = (Double)attributes.get(
				"chg_pct_high_52week");

		if (chg_pct_high_52week != null) {
			setChg_pct_high_52week(chg_pct_high_52week);
		}

		Double chg_pct_low_52week = (Double)attributes.get("chg_pct_low_52week");

		if (chg_pct_low_52week != null) {
			setChg_pct_low_52week(chg_pct_low_52week);
		}

		Double chg_pct_1yr = (Double)attributes.get("chg_pct_1yr");

		if (chg_pct_1yr != null) {
			setChg_pct_1yr(chg_pct_1yr);
		}

		Double chg_trr_5yr = (Double)attributes.get("chg_trr_5yr");

		if (chg_trr_5yr != null) {
			setChg_trr_5yr(chg_trr_5yr);
		}

		Double current_price = (Double)attributes.get("current_price");

		if (current_price != null) {
			setCurrent_price(current_price);
		}

		Double last_price = (Double)attributes.get("last_price");

		if (last_price != null) {
			setLast_price(last_price);
		}

		Double bid_price = (Double)attributes.get("bid_price");

		if (bid_price != null) {
			setBid_price(bid_price);
		}

		Double ask_price = (Double)attributes.get("ask_price");

		if (ask_price != null) {
			setAsk_price(ask_price);
		}

		String security_des = (String)attributes.get("security_des");

		if (security_des != null) {
			setSecurity_des(security_des);
		}

		String parent_comp_name = (String)attributes.get("parent_comp_name");

		if (parent_comp_name != null) {
			setParent_comp_name(parent_comp_name);
		}

		Integer security_class = (Integer)attributes.get("security_class");

		if (security_class != null) {
			setSecurity_class(security_class);
		}

		Double volatility_30d = (Double)attributes.get("volatility_30d");

		if (volatility_30d != null) {
			setVolatility_30d(volatility_30d);
		}

		Double volatility_90d = (Double)attributes.get("volatility_90d");

		if (volatility_90d != null) {
			setVolatility_90d(volatility_90d);
		}

		Double volatility_180d = (Double)attributes.get("volatility_180d");

		if (volatility_180d != null) {
			setVolatility_180d(volatility_180d);
		}

		Double volatility_360d = (Double)attributes.get("volatility_360d");

		if (volatility_360d != null) {
			setVolatility_360d(volatility_360d);
		}

		String currency = (String)attributes.get("currency");

		if (currency != null) {
			setCurrency(currency);
		}

		Long country = (Long)attributes.get("country");

		if (country != null) {
			setCountry(country);
		}

		Long country_of_risk = (Long)attributes.get("country_of_risk");

		if (country_of_risk != null) {
			setCountry_of_risk(country_of_risk);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}
	}

	@JSON
	@Override
	public long getAssetId() {
		return _assetId;
	}

	@Override
	public void setAssetId(long assetId) {
		_assetId = assetId;
	}

	@JSON
	@Override
	public String getSecurity_ticker() {
		if (_security_ticker == null) {
			return StringPool.BLANK;
		}
		else {
			return _security_ticker;
		}
	}

	@Override
	public void setSecurity_ticker(String security_ticker) {
		_columnBitmask |= SECURITY_TICKER_COLUMN_BITMASK;

		if (_originalSecurity_ticker == null) {
			_originalSecurity_ticker = _security_ticker;
		}

		_security_ticker = security_ticker;
	}

	public String getOriginalSecurity_ticker() {
		return GetterUtil.getString(_originalSecurity_ticker);
	}

	@JSON
	@Override
	public String getId_cusip() {
		if (_id_cusip == null) {
			return StringPool.BLANK;
		}
		else {
			return _id_cusip;
		}
	}

	@Override
	public void setId_cusip(String id_cusip) {
		_id_cusip = id_cusip;
	}

	@JSON
	@Override
	public String getId_isin() {
		if (_id_isin == null) {
			return StringPool.BLANK;
		}
		else {
			return _id_isin;
		}
	}

	@Override
	public void setId_isin(String id_isin) {
		_columnBitmask |= ID_ISIN_COLUMN_BITMASK;

		if (_originalId_isin == null) {
			_originalId_isin = _id_isin;
		}

		_id_isin = id_isin;
	}

	public String getOriginalId_isin() {
		return GetterUtil.getString(_originalId_isin);
	}

	@JSON
	@Override
	public String getId_bb_global() {
		if (_id_bb_global == null) {
			return StringPool.BLANK;
		}
		else {
			return _id_bb_global;
		}
	}

	@Override
	public void setId_bb_global(String id_bb_global) {
		_id_bb_global = id_bb_global;
	}

	@JSON
	@Override
	public long getId_bb_sec_num_src() {
		return _id_bb_sec_num_src;
	}

	@Override
	public void setId_bb_sec_num_src(long id_bb_sec_num_src) {
		_id_bb_sec_num_src = id_bb_sec_num_src;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public double getChg_pct_mtd() {
		return _chg_pct_mtd;
	}

	@Override
	public void setChg_pct_mtd(double chg_pct_mtd) {
		_chg_pct_mtd = chg_pct_mtd;
	}

	@JSON
	@Override
	public double getChg_pct_5d() {
		return _chg_pct_5d;
	}

	@Override
	public void setChg_pct_5d(double chg_pct_5d) {
		_chg_pct_5d = chg_pct_5d;
	}

	@JSON
	@Override
	public double getChg_pct_1m() {
		return _chg_pct_1m;
	}

	@Override
	public void setChg_pct_1m(double chg_pct_1m) {
		_chg_pct_1m = chg_pct_1m;
	}

	@JSON
	@Override
	public double getChg_pct_3m() {
		return _chg_pct_3m;
	}

	@Override
	public void setChg_pct_3m(double chg_pct_3m) {
		_chg_pct_3m = chg_pct_3m;
	}

	@JSON
	@Override
	public double getChg_pct_6m() {
		return _chg_pct_6m;
	}

	@Override
	public void setChg_pct_6m(double chg_pct_6m) {
		_chg_pct_6m = chg_pct_6m;
	}

	@JSON
	@Override
	public double getChg_pct_ytd() {
		return _chg_pct_ytd;
	}

	@Override
	public void setChg_pct_ytd(double chg_pct_ytd) {
		_chg_pct_ytd = chg_pct_ytd;
	}

	@JSON
	@Override
	public double getChg_pct_high_52week() {
		return _chg_pct_high_52week;
	}

	@Override
	public void setChg_pct_high_52week(double chg_pct_high_52week) {
		_chg_pct_high_52week = chg_pct_high_52week;
	}

	@JSON
	@Override
	public double getChg_pct_low_52week() {
		return _chg_pct_low_52week;
	}

	@Override
	public void setChg_pct_low_52week(double chg_pct_low_52week) {
		_chg_pct_low_52week = chg_pct_low_52week;
	}

	@JSON
	@Override
	public double getChg_pct_1yr() {
		return _chg_pct_1yr;
	}

	@Override
	public void setChg_pct_1yr(double chg_pct_1yr) {
		_chg_pct_1yr = chg_pct_1yr;
	}

	@JSON
	@Override
	public double getChg_trr_5yr() {
		return _chg_trr_5yr;
	}

	@Override
	public void setChg_trr_5yr(double chg_trr_5yr) {
		_chg_trr_5yr = chg_trr_5yr;
	}

	@JSON
	@Override
	public double getCurrent_price() {
		return _current_price;
	}

	@Override
	public void setCurrent_price(double current_price) {
		_current_price = current_price;
	}

	@JSON
	@Override
	public double getLast_price() {
		return _last_price;
	}

	@Override
	public void setLast_price(double last_price) {
		_last_price = last_price;
	}

	@JSON
	@Override
	public double getBid_price() {
		return _bid_price;
	}

	@Override
	public void setBid_price(double bid_price) {
		_bid_price = bid_price;
	}

	@JSON
	@Override
	public double getAsk_price() {
		return _ask_price;
	}

	@Override
	public void setAsk_price(double ask_price) {
		_ask_price = ask_price;
	}

	@JSON
	@Override
	public String getSecurity_des() {
		if (_security_des == null) {
			return StringPool.BLANK;
		}
		else {
			return _security_des;
		}
	}

	@Override
	public void setSecurity_des(String security_des) {
		_security_des = security_des;
	}

	@JSON
	@Override
	public String getParent_comp_name() {
		if (_parent_comp_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _parent_comp_name;
		}
	}

	@Override
	public void setParent_comp_name(String parent_comp_name) {
		_parent_comp_name = parent_comp_name;
	}

	@JSON
	@Override
	public int getSecurity_class() {
		return _security_class;
	}

	@Override
	public void setSecurity_class(int security_class) {
		_security_class = security_class;
	}

	@JSON
	@Override
	public double getVolatility_30d() {
		return _volatility_30d;
	}

	@Override
	public void setVolatility_30d(double volatility_30d) {
		_volatility_30d = volatility_30d;
	}

	@JSON
	@Override
	public double getVolatility_90d() {
		return _volatility_90d;
	}

	@Override
	public void setVolatility_90d(double volatility_90d) {
		_volatility_90d = volatility_90d;
	}

	@JSON
	@Override
	public double getVolatility_180d() {
		return _volatility_180d;
	}

	@Override
	public void setVolatility_180d(double volatility_180d) {
		_volatility_180d = volatility_180d;
	}

	@JSON
	@Override
	public double getVolatility_360d() {
		return _volatility_360d;
	}

	@Override
	public void setVolatility_360d(double volatility_360d) {
		_volatility_360d = volatility_360d;
	}

	@JSON
	@Override
	public String getCurrency() {
		if (_currency == null) {
			return StringPool.BLANK;
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		_currency = currency;
	}

	@JSON
	@Override
	public long getCountry() {
		return _country;
	}

	@Override
	public void setCountry(long country) {
		_country = country;
	}

	@JSON
	@Override
	public long getCountry_of_risk() {
		return _country_of_risk;
	}

	@Override
	public void setCountry_of_risk(long country_of_risk) {
		_country_of_risk = country_of_risk;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Asset.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Asset toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Asset)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetImpl assetImpl = new AssetImpl();

		assetImpl.setAssetId(getAssetId());
		assetImpl.setSecurity_ticker(getSecurity_ticker());
		assetImpl.setId_cusip(getId_cusip());
		assetImpl.setId_isin(getId_isin());
		assetImpl.setId_bb_global(getId_bb_global());
		assetImpl.setId_bb_sec_num_src(getId_bb_sec_num_src());
		assetImpl.setName(getName());
		assetImpl.setChg_pct_mtd(getChg_pct_mtd());
		assetImpl.setChg_pct_5d(getChg_pct_5d());
		assetImpl.setChg_pct_1m(getChg_pct_1m());
		assetImpl.setChg_pct_3m(getChg_pct_3m());
		assetImpl.setChg_pct_6m(getChg_pct_6m());
		assetImpl.setChg_pct_ytd(getChg_pct_ytd());
		assetImpl.setChg_pct_high_52week(getChg_pct_high_52week());
		assetImpl.setChg_pct_low_52week(getChg_pct_low_52week());
		assetImpl.setChg_pct_1yr(getChg_pct_1yr());
		assetImpl.setChg_trr_5yr(getChg_trr_5yr());
		assetImpl.setCurrent_price(getCurrent_price());
		assetImpl.setLast_price(getLast_price());
		assetImpl.setBid_price(getBid_price());
		assetImpl.setAsk_price(getAsk_price());
		assetImpl.setSecurity_des(getSecurity_des());
		assetImpl.setParent_comp_name(getParent_comp_name());
		assetImpl.setSecurity_class(getSecurity_class());
		assetImpl.setVolatility_30d(getVolatility_30d());
		assetImpl.setVolatility_90d(getVolatility_90d());
		assetImpl.setVolatility_180d(getVolatility_180d());
		assetImpl.setVolatility_360d(getVolatility_360d());
		assetImpl.setCurrency(getCurrency());
		assetImpl.setCountry(getCountry());
		assetImpl.setCountry_of_risk(getCountry_of_risk());
		assetImpl.setCreateDate(getCreateDate());
		assetImpl.setModifiedDate(getModifiedDate());
		assetImpl.setCompanyId(getCompanyId());
		assetImpl.setUserId(getUserId());
		assetImpl.setUserName(getUserName());

		assetImpl.resetOriginalValues();

		return assetImpl;
	}

	@Override
	public int compareTo(Asset asset) {
		long primaryKey = asset.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Asset)) {
			return false;
		}

		Asset asset = (Asset)obj;

		long primaryKey = asset.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AssetModelImpl assetModelImpl = this;

		assetModelImpl._originalSecurity_ticker = assetModelImpl._security_ticker;

		assetModelImpl._originalId_isin = assetModelImpl._id_isin;

		assetModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Asset> toCacheModel() {
		AssetCacheModel assetCacheModel = new AssetCacheModel();

		assetCacheModel.assetId = getAssetId();

		assetCacheModel.security_ticker = getSecurity_ticker();

		String security_ticker = assetCacheModel.security_ticker;

		if ((security_ticker != null) && (security_ticker.length() == 0)) {
			assetCacheModel.security_ticker = null;
		}

		assetCacheModel.id_cusip = getId_cusip();

		String id_cusip = assetCacheModel.id_cusip;

		if ((id_cusip != null) && (id_cusip.length() == 0)) {
			assetCacheModel.id_cusip = null;
		}

		assetCacheModel.id_isin = getId_isin();

		String id_isin = assetCacheModel.id_isin;

		if ((id_isin != null) && (id_isin.length() == 0)) {
			assetCacheModel.id_isin = null;
		}

		assetCacheModel.id_bb_global = getId_bb_global();

		String id_bb_global = assetCacheModel.id_bb_global;

		if ((id_bb_global != null) && (id_bb_global.length() == 0)) {
			assetCacheModel.id_bb_global = null;
		}

		assetCacheModel.id_bb_sec_num_src = getId_bb_sec_num_src();

		assetCacheModel.name = getName();

		String name = assetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			assetCacheModel.name = null;
		}

		assetCacheModel.chg_pct_mtd = getChg_pct_mtd();

		assetCacheModel.chg_pct_5d = getChg_pct_5d();

		assetCacheModel.chg_pct_1m = getChg_pct_1m();

		assetCacheModel.chg_pct_3m = getChg_pct_3m();

		assetCacheModel.chg_pct_6m = getChg_pct_6m();

		assetCacheModel.chg_pct_ytd = getChg_pct_ytd();

		assetCacheModel.chg_pct_high_52week = getChg_pct_high_52week();

		assetCacheModel.chg_pct_low_52week = getChg_pct_low_52week();

		assetCacheModel.chg_pct_1yr = getChg_pct_1yr();

		assetCacheModel.chg_trr_5yr = getChg_trr_5yr();

		assetCacheModel.current_price = getCurrent_price();

		assetCacheModel.last_price = getLast_price();

		assetCacheModel.bid_price = getBid_price();

		assetCacheModel.ask_price = getAsk_price();

		assetCacheModel.security_des = getSecurity_des();

		String security_des = assetCacheModel.security_des;

		if ((security_des != null) && (security_des.length() == 0)) {
			assetCacheModel.security_des = null;
		}

		assetCacheModel.parent_comp_name = getParent_comp_name();

		String parent_comp_name = assetCacheModel.parent_comp_name;

		if ((parent_comp_name != null) && (parent_comp_name.length() == 0)) {
			assetCacheModel.parent_comp_name = null;
		}

		assetCacheModel.security_class = getSecurity_class();

		assetCacheModel.volatility_30d = getVolatility_30d();

		assetCacheModel.volatility_90d = getVolatility_90d();

		assetCacheModel.volatility_180d = getVolatility_180d();

		assetCacheModel.volatility_360d = getVolatility_360d();

		assetCacheModel.currency = getCurrency();

		String currency = assetCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			assetCacheModel.currency = null;
		}

		assetCacheModel.country = getCountry();

		assetCacheModel.country_of_risk = getCountry_of_risk();

		Date createDate = getCreateDate();

		if (createDate != null) {
			assetCacheModel.createDate = createDate.getTime();
		}
		else {
			assetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			assetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			assetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		assetCacheModel.companyId = getCompanyId();

		assetCacheModel.userId = getUserId();

		assetCacheModel.userName = getUserName();

		String userName = assetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			assetCacheModel.userName = null;
		}

		return assetCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(73);

		sb.append("{assetId=");
		sb.append(getAssetId());
		sb.append(", security_ticker=");
		sb.append(getSecurity_ticker());
		sb.append(", id_cusip=");
		sb.append(getId_cusip());
		sb.append(", id_isin=");
		sb.append(getId_isin());
		sb.append(", id_bb_global=");
		sb.append(getId_bb_global());
		sb.append(", id_bb_sec_num_src=");
		sb.append(getId_bb_sec_num_src());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", chg_pct_mtd=");
		sb.append(getChg_pct_mtd());
		sb.append(", chg_pct_5d=");
		sb.append(getChg_pct_5d());
		sb.append(", chg_pct_1m=");
		sb.append(getChg_pct_1m());
		sb.append(", chg_pct_3m=");
		sb.append(getChg_pct_3m());
		sb.append(", chg_pct_6m=");
		sb.append(getChg_pct_6m());
		sb.append(", chg_pct_ytd=");
		sb.append(getChg_pct_ytd());
		sb.append(", chg_pct_high_52week=");
		sb.append(getChg_pct_high_52week());
		sb.append(", chg_pct_low_52week=");
		sb.append(getChg_pct_low_52week());
		sb.append(", chg_pct_1yr=");
		sb.append(getChg_pct_1yr());
		sb.append(", chg_trr_5yr=");
		sb.append(getChg_trr_5yr());
		sb.append(", current_price=");
		sb.append(getCurrent_price());
		sb.append(", last_price=");
		sb.append(getLast_price());
		sb.append(", bid_price=");
		sb.append(getBid_price());
		sb.append(", ask_price=");
		sb.append(getAsk_price());
		sb.append(", security_des=");
		sb.append(getSecurity_des());
		sb.append(", parent_comp_name=");
		sb.append(getParent_comp_name());
		sb.append(", security_class=");
		sb.append(getSecurity_class());
		sb.append(", volatility_30d=");
		sb.append(getVolatility_30d());
		sb.append(", volatility_90d=");
		sb.append(getVolatility_90d());
		sb.append(", volatility_180d=");
		sb.append(getVolatility_180d());
		sb.append(", volatility_360d=");
		sb.append(getVolatility_360d());
		sb.append(", currency=");
		sb.append(getCurrency());
		sb.append(", country=");
		sb.append(getCountry());
		sb.append(", country_of_risk=");
		sb.append(getCountry_of_risk());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(112);

		sb.append("<model><model-name>");
		sb.append("com.fingence.slayer.model.Asset");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assetId</column-name><column-value><![CDATA[");
		sb.append(getAssetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>security_ticker</column-name><column-value><![CDATA[");
		sb.append(getSecurity_ticker());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_cusip</column-name><column-value><![CDATA[");
		sb.append(getId_cusip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_isin</column-name><column-value><![CDATA[");
		sb.append(getId_isin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_bb_global</column-name><column-value><![CDATA[");
		sb.append(getId_bb_global());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_bb_sec_num_src</column-name><column-value><![CDATA[");
		sb.append(getId_bb_sec_num_src());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_mtd</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_mtd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_5d</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_5d());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_1m</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_1m());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_3m</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_3m());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_6m</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_6m());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_ytd</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_ytd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_high_52week</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_high_52week());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_low_52week</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_low_52week());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_pct_1yr</column-name><column-value><![CDATA[");
		sb.append(getChg_pct_1yr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chg_trr_5yr</column-name><column-value><![CDATA[");
		sb.append(getChg_trr_5yr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>current_price</column-name><column-value><![CDATA[");
		sb.append(getCurrent_price());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>last_price</column-name><column-value><![CDATA[");
		sb.append(getLast_price());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bid_price</column-name><column-value><![CDATA[");
		sb.append(getBid_price());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ask_price</column-name><column-value><![CDATA[");
		sb.append(getAsk_price());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>security_des</column-name><column-value><![CDATA[");
		sb.append(getSecurity_des());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parent_comp_name</column-name><column-value><![CDATA[");
		sb.append(getParent_comp_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>security_class</column-name><column-value><![CDATA[");
		sb.append(getSecurity_class());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>volatility_30d</column-name><column-value><![CDATA[");
		sb.append(getVolatility_30d());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>volatility_90d</column-name><column-value><![CDATA[");
		sb.append(getVolatility_90d());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>volatility_180d</column-name><column-value><![CDATA[");
		sb.append(getVolatility_180d());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>volatility_360d</column-name><column-value><![CDATA[");
		sb.append(getVolatility_360d());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currency</column-name><column-value><![CDATA[");
		sb.append(getCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>country</column-name><column-value><![CDATA[");
		sb.append(getCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>country_of_risk</column-name><column-value><![CDATA[");
		sb.append(getCountry_of_risk());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Asset.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Asset.class };
	private long _assetId;
	private String _security_ticker;
	private String _originalSecurity_ticker;
	private String _id_cusip;
	private String _id_isin;
	private String _originalId_isin;
	private String _id_bb_global;
	private long _id_bb_sec_num_src;
	private String _name;
	private double _chg_pct_mtd;
	private double _chg_pct_5d;
	private double _chg_pct_1m;
	private double _chg_pct_3m;
	private double _chg_pct_6m;
	private double _chg_pct_ytd;
	private double _chg_pct_high_52week;
	private double _chg_pct_low_52week;
	private double _chg_pct_1yr;
	private double _chg_trr_5yr;
	private double _current_price;
	private double _last_price;
	private double _bid_price;
	private double _ask_price;
	private String _security_des;
	private String _parent_comp_name;
	private int _security_class;
	private double _volatility_30d;
	private double _volatility_90d;
	private double _volatility_180d;
	private double _volatility_360d;
	private String _currency;
	private long _country;
	private long _country_of_risk;
	private Date _createDate;
	private Date _modifiedDate;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private long _columnBitmask;
	private Asset _escapedModel;
}