/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fingence.slayer.model.impl;

import com.fingence.slayer.model.Equity;
import com.fingence.slayer.model.EquityModel;
import com.fingence.slayer.model.EquitySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Equity service. Represents a row in the &quot;fing_Equity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.fingence.slayer.model.EquityModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EquityImpl}.
 * </p>
 *
 * @author Ahmed Hasan
 * @see EquityImpl
 * @see com.fingence.slayer.model.Equity
 * @see com.fingence.slayer.model.EquityModel
 * @generated
 */
@JSON(strict = true)
public class EquityModelImpl extends BaseModelImpl<Equity>
	implements EquityModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a equity model instance should use the {@link com.fingence.slayer.model.Equity} interface instead.
	 */
	public static final String TABLE_NAME = "fing_Equity";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assetId", Types.BIGINT },
			{ "eqy_alpha", Types.DOUBLE },
			{ "dividend_yield", Types.DOUBLE },
			{ "eqy_dvd_yld_12m", Types.DOUBLE },
			{ "eqy_dvd_yld_es", Types.DOUBLE },
			{ "dvd_payout_ratio", Types.DOUBLE },
			{ "pe_ratio", Types.DOUBLE },
			{ "tot_debt_to_com_eqy", Types.DOUBLE },
			{ "ebitda_to_revenue", Types.DOUBLE },
			{ "trail_12m_prof_margin", Types.DOUBLE },
			{ "best_current_ev_best_opp", Types.DOUBLE },
			{ "eqy_beta", Types.DOUBLE },
			{ "return_sharpe_ratio", Types.DOUBLE },
			{ "eqy_sharpe_ratio_1yr", Types.DOUBLE },
			{ "eqy_sharpe_ratio_3yr", Types.DOUBLE },
			{ "eqy_sharpe_ratio_5yr", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table fing_Equity (assetId LONG not null primary key,eqy_alpha DOUBLE,dividend_yield DOUBLE,eqy_dvd_yld_12m DOUBLE,eqy_dvd_yld_es DOUBLE,dvd_payout_ratio DOUBLE,pe_ratio DOUBLE,tot_debt_to_com_eqy DOUBLE,ebitda_to_revenue DOUBLE,trail_12m_prof_margin DOUBLE,best_current_ev_best_opp DOUBLE,eqy_beta DOUBLE,return_sharpe_ratio DOUBLE,eqy_sharpe_ratio_1yr DOUBLE,eqy_sharpe_ratio_3yr DOUBLE,eqy_sharpe_ratio_5yr DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table fing_Equity";
	public static final String ORDER_BY_JPQL = " ORDER BY equity.assetId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY fing_Equity.assetId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fingence.slayer.model.Equity"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fingence.slayer.model.Equity"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Equity toModel(EquitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Equity model = new EquityImpl();

		model.setAssetId(soapModel.getAssetId());
		model.setEqy_alpha(soapModel.getEqy_alpha());
		model.setDividend_yield(soapModel.getDividend_yield());
		model.setEqy_dvd_yld_12m(soapModel.getEqy_dvd_yld_12m());
		model.setEqy_dvd_yld_es(soapModel.getEqy_dvd_yld_es());
		model.setDvd_payout_ratio(soapModel.getDvd_payout_ratio());
		model.setPe_ratio(soapModel.getPe_ratio());
		model.setTot_debt_to_com_eqy(soapModel.getTot_debt_to_com_eqy());
		model.setEbitda_to_revenue(soapModel.getEbitda_to_revenue());
		model.setTrail_12m_prof_margin(soapModel.getTrail_12m_prof_margin());
		model.setBest_current_ev_best_opp(soapModel.getBest_current_ev_best_opp());
		model.setEqy_beta(soapModel.getEqy_beta());
		model.setReturn_sharpe_ratio(soapModel.getReturn_sharpe_ratio());
		model.setEqy_sharpe_ratio_1yr(soapModel.getEqy_sharpe_ratio_1yr());
		model.setEqy_sharpe_ratio_3yr(soapModel.getEqy_sharpe_ratio_3yr());
		model.setEqy_sharpe_ratio_5yr(soapModel.getEqy_sharpe_ratio_5yr());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Equity> toModels(EquitySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Equity> models = new ArrayList<Equity>(soapModels.length);

		for (EquitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.fingence.slayer.model.Equity"));

	public EquityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Equity.class;
	}

	@Override
	public String getModelClassName() {
		return Equity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assetId", getAssetId());
		attributes.put("eqy_alpha", getEqy_alpha());
		attributes.put("dividend_yield", getDividend_yield());
		attributes.put("eqy_dvd_yld_12m", getEqy_dvd_yld_12m());
		attributes.put("eqy_dvd_yld_es", getEqy_dvd_yld_es());
		attributes.put("dvd_payout_ratio", getDvd_payout_ratio());
		attributes.put("pe_ratio", getPe_ratio());
		attributes.put("tot_debt_to_com_eqy", getTot_debt_to_com_eqy());
		attributes.put("ebitda_to_revenue", getEbitda_to_revenue());
		attributes.put("trail_12m_prof_margin", getTrail_12m_prof_margin());
		attributes.put("best_current_ev_best_opp", getBest_current_ev_best_opp());
		attributes.put("eqy_beta", getEqy_beta());
		attributes.put("return_sharpe_ratio", getReturn_sharpe_ratio());
		attributes.put("eqy_sharpe_ratio_1yr", getEqy_sharpe_ratio_1yr());
		attributes.put("eqy_sharpe_ratio_3yr", getEqy_sharpe_ratio_3yr());
		attributes.put("eqy_sharpe_ratio_5yr", getEqy_sharpe_ratio_5yr());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assetId = (Long)attributes.get("assetId");

		if (assetId != null) {
			setAssetId(assetId);
		}

		Double eqy_alpha = (Double)attributes.get("eqy_alpha");

		if (eqy_alpha != null) {
			setEqy_alpha(eqy_alpha);
		}

		Double dividend_yield = (Double)attributes.get("dividend_yield");

		if (dividend_yield != null) {
			setDividend_yield(dividend_yield);
		}

		Double eqy_dvd_yld_12m = (Double)attributes.get("eqy_dvd_yld_12m");

		if (eqy_dvd_yld_12m != null) {
			setEqy_dvd_yld_12m(eqy_dvd_yld_12m);
		}

		Double eqy_dvd_yld_es = (Double)attributes.get("eqy_dvd_yld_es");

		if (eqy_dvd_yld_es != null) {
			setEqy_dvd_yld_es(eqy_dvd_yld_es);
		}

		Double dvd_payout_ratio = (Double)attributes.get("dvd_payout_ratio");

		if (dvd_payout_ratio != null) {
			setDvd_payout_ratio(dvd_payout_ratio);
		}

		Double pe_ratio = (Double)attributes.get("pe_ratio");

		if (pe_ratio != null) {
			setPe_ratio(pe_ratio);
		}

		Double tot_debt_to_com_eqy = (Double)attributes.get(
				"tot_debt_to_com_eqy");

		if (tot_debt_to_com_eqy != null) {
			setTot_debt_to_com_eqy(tot_debt_to_com_eqy);
		}

		Double ebitda_to_revenue = (Double)attributes.get("ebitda_to_revenue");

		if (ebitda_to_revenue != null) {
			setEbitda_to_revenue(ebitda_to_revenue);
		}

		Double trail_12m_prof_margin = (Double)attributes.get(
				"trail_12m_prof_margin");

		if (trail_12m_prof_margin != null) {
			setTrail_12m_prof_margin(trail_12m_prof_margin);
		}

		Double best_current_ev_best_opp = (Double)attributes.get(
				"best_current_ev_best_opp");

		if (best_current_ev_best_opp != null) {
			setBest_current_ev_best_opp(best_current_ev_best_opp);
		}

		Double eqy_beta = (Double)attributes.get("eqy_beta");

		if (eqy_beta != null) {
			setEqy_beta(eqy_beta);
		}

		Double return_sharpe_ratio = (Double)attributes.get(
				"return_sharpe_ratio");

		if (return_sharpe_ratio != null) {
			setReturn_sharpe_ratio(return_sharpe_ratio);
		}

		Double eqy_sharpe_ratio_1yr = (Double)attributes.get(
				"eqy_sharpe_ratio_1yr");

		if (eqy_sharpe_ratio_1yr != null) {
			setEqy_sharpe_ratio_1yr(eqy_sharpe_ratio_1yr);
		}

		Double eqy_sharpe_ratio_3yr = (Double)attributes.get(
				"eqy_sharpe_ratio_3yr");

		if (eqy_sharpe_ratio_3yr != null) {
			setEqy_sharpe_ratio_3yr(eqy_sharpe_ratio_3yr);
		}

		Double eqy_sharpe_ratio_5yr = (Double)attributes.get(
				"eqy_sharpe_ratio_5yr");

		if (eqy_sharpe_ratio_5yr != null) {
			setEqy_sharpe_ratio_5yr(eqy_sharpe_ratio_5yr);
		}
	}

	@JSON
	@Override
	public long getAssetId() {
		return _assetId;
	}

	@Override
	public void setAssetId(long assetId) {
		_assetId = assetId;
	}

	@JSON
	@Override
	public double getEqy_alpha() {
		return _eqy_alpha;
	}

	@Override
	public void setEqy_alpha(double eqy_alpha) {
		_eqy_alpha = eqy_alpha;
	}

	@JSON
	@Override
	public double getDividend_yield() {
		return _dividend_yield;
	}

	@Override
	public void setDividend_yield(double dividend_yield) {
		_dividend_yield = dividend_yield;
	}

	@JSON
	@Override
	public double getEqy_dvd_yld_12m() {
		return _eqy_dvd_yld_12m;
	}

	@Override
	public void setEqy_dvd_yld_12m(double eqy_dvd_yld_12m) {
		_eqy_dvd_yld_12m = eqy_dvd_yld_12m;
	}

	@JSON
	@Override
	public double getEqy_dvd_yld_es() {
		return _eqy_dvd_yld_es;
	}

	@Override
	public void setEqy_dvd_yld_es(double eqy_dvd_yld_es) {
		_eqy_dvd_yld_es = eqy_dvd_yld_es;
	}

	@JSON
	@Override
	public double getDvd_payout_ratio() {
		return _dvd_payout_ratio;
	}

	@Override
	public void setDvd_payout_ratio(double dvd_payout_ratio) {
		_dvd_payout_ratio = dvd_payout_ratio;
	}

	@JSON
	@Override
	public double getPe_ratio() {
		return _pe_ratio;
	}

	@Override
	public void setPe_ratio(double pe_ratio) {
		_pe_ratio = pe_ratio;
	}

	@JSON
	@Override
	public double getTot_debt_to_com_eqy() {
		return _tot_debt_to_com_eqy;
	}

	@Override
	public void setTot_debt_to_com_eqy(double tot_debt_to_com_eqy) {
		_tot_debt_to_com_eqy = tot_debt_to_com_eqy;
	}

	@JSON
	@Override
	public double getEbitda_to_revenue() {
		return _ebitda_to_revenue;
	}

	@Override
	public void setEbitda_to_revenue(double ebitda_to_revenue) {
		_ebitda_to_revenue = ebitda_to_revenue;
	}

	@JSON
	@Override
	public double getTrail_12m_prof_margin() {
		return _trail_12m_prof_margin;
	}

	@Override
	public void setTrail_12m_prof_margin(double trail_12m_prof_margin) {
		_trail_12m_prof_margin = trail_12m_prof_margin;
	}

	@JSON
	@Override
	public double getBest_current_ev_best_opp() {
		return _best_current_ev_best_opp;
	}

	@Override
	public void setBest_current_ev_best_opp(double best_current_ev_best_opp) {
		_best_current_ev_best_opp = best_current_ev_best_opp;
	}

	@JSON
	@Override
	public double getEqy_beta() {
		return _eqy_beta;
	}

	@Override
	public void setEqy_beta(double eqy_beta) {
		_eqy_beta = eqy_beta;
	}

	@JSON
	@Override
	public double getReturn_sharpe_ratio() {
		return _return_sharpe_ratio;
	}

	@Override
	public void setReturn_sharpe_ratio(double return_sharpe_ratio) {
		_return_sharpe_ratio = return_sharpe_ratio;
	}

	@JSON
	@Override
	public double getEqy_sharpe_ratio_1yr() {
		return _eqy_sharpe_ratio_1yr;
	}

	@Override
	public void setEqy_sharpe_ratio_1yr(double eqy_sharpe_ratio_1yr) {
		_eqy_sharpe_ratio_1yr = eqy_sharpe_ratio_1yr;
	}

	@JSON
	@Override
	public double getEqy_sharpe_ratio_3yr() {
		return _eqy_sharpe_ratio_3yr;
	}

	@Override
	public void setEqy_sharpe_ratio_3yr(double eqy_sharpe_ratio_3yr) {
		_eqy_sharpe_ratio_3yr = eqy_sharpe_ratio_3yr;
	}

	@JSON
	@Override
	public double getEqy_sharpe_ratio_5yr() {
		return _eqy_sharpe_ratio_5yr;
	}

	@Override
	public void setEqy_sharpe_ratio_5yr(double eqy_sharpe_ratio_5yr) {
		_eqy_sharpe_ratio_5yr = eqy_sharpe_ratio_5yr;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Equity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Equity toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Equity)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EquityImpl equityImpl = new EquityImpl();

		equityImpl.setAssetId(getAssetId());
		equityImpl.setEqy_alpha(getEqy_alpha());
		equityImpl.setDividend_yield(getDividend_yield());
		equityImpl.setEqy_dvd_yld_12m(getEqy_dvd_yld_12m());
		equityImpl.setEqy_dvd_yld_es(getEqy_dvd_yld_es());
		equityImpl.setDvd_payout_ratio(getDvd_payout_ratio());
		equityImpl.setPe_ratio(getPe_ratio());
		equityImpl.setTot_debt_to_com_eqy(getTot_debt_to_com_eqy());
		equityImpl.setEbitda_to_revenue(getEbitda_to_revenue());
		equityImpl.setTrail_12m_prof_margin(getTrail_12m_prof_margin());
		equityImpl.setBest_current_ev_best_opp(getBest_current_ev_best_opp());
		equityImpl.setEqy_beta(getEqy_beta());
		equityImpl.setReturn_sharpe_ratio(getReturn_sharpe_ratio());
		equityImpl.setEqy_sharpe_ratio_1yr(getEqy_sharpe_ratio_1yr());
		equityImpl.setEqy_sharpe_ratio_3yr(getEqy_sharpe_ratio_3yr());
		equityImpl.setEqy_sharpe_ratio_5yr(getEqy_sharpe_ratio_5yr());

		equityImpl.resetOriginalValues();

		return equityImpl;
	}

	@Override
	public int compareTo(Equity equity) {
		long primaryKey = equity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Equity)) {
			return false;
		}

		Equity equity = (Equity)obj;

		long primaryKey = equity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Equity> toCacheModel() {
		EquityCacheModel equityCacheModel = new EquityCacheModel();

		equityCacheModel.assetId = getAssetId();

		equityCacheModel.eqy_alpha = getEqy_alpha();

		equityCacheModel.dividend_yield = getDividend_yield();

		equityCacheModel.eqy_dvd_yld_12m = getEqy_dvd_yld_12m();

		equityCacheModel.eqy_dvd_yld_es = getEqy_dvd_yld_es();

		equityCacheModel.dvd_payout_ratio = getDvd_payout_ratio();

		equityCacheModel.pe_ratio = getPe_ratio();

		equityCacheModel.tot_debt_to_com_eqy = getTot_debt_to_com_eqy();

		equityCacheModel.ebitda_to_revenue = getEbitda_to_revenue();

		equityCacheModel.trail_12m_prof_margin = getTrail_12m_prof_margin();

		equityCacheModel.best_current_ev_best_opp = getBest_current_ev_best_opp();

		equityCacheModel.eqy_beta = getEqy_beta();

		equityCacheModel.return_sharpe_ratio = getReturn_sharpe_ratio();

		equityCacheModel.eqy_sharpe_ratio_1yr = getEqy_sharpe_ratio_1yr();

		equityCacheModel.eqy_sharpe_ratio_3yr = getEqy_sharpe_ratio_3yr();

		equityCacheModel.eqy_sharpe_ratio_5yr = getEqy_sharpe_ratio_5yr();

		return equityCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{assetId=");
		sb.append(getAssetId());
		sb.append(", eqy_alpha=");
		sb.append(getEqy_alpha());
		sb.append(", dividend_yield=");
		sb.append(getDividend_yield());
		sb.append(", eqy_dvd_yld_12m=");
		sb.append(getEqy_dvd_yld_12m());
		sb.append(", eqy_dvd_yld_es=");
		sb.append(getEqy_dvd_yld_es());
		sb.append(", dvd_payout_ratio=");
		sb.append(getDvd_payout_ratio());
		sb.append(", pe_ratio=");
		sb.append(getPe_ratio());
		sb.append(", tot_debt_to_com_eqy=");
		sb.append(getTot_debt_to_com_eqy());
		sb.append(", ebitda_to_revenue=");
		sb.append(getEbitda_to_revenue());
		sb.append(", trail_12m_prof_margin=");
		sb.append(getTrail_12m_prof_margin());
		sb.append(", best_current_ev_best_opp=");
		sb.append(getBest_current_ev_best_opp());
		sb.append(", eqy_beta=");
		sb.append(getEqy_beta());
		sb.append(", return_sharpe_ratio=");
		sb.append(getReturn_sharpe_ratio());
		sb.append(", eqy_sharpe_ratio_1yr=");
		sb.append(getEqy_sharpe_ratio_1yr());
		sb.append(", eqy_sharpe_ratio_3yr=");
		sb.append(getEqy_sharpe_ratio_3yr());
		sb.append(", eqy_sharpe_ratio_5yr=");
		sb.append(getEqy_sharpe_ratio_5yr());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("com.fingence.slayer.model.Equity");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assetId</column-name><column-value><![CDATA[");
		sb.append(getAssetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eqy_alpha</column-name><column-value><![CDATA[");
		sb.append(getEqy_alpha());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dividend_yield</column-name><column-value><![CDATA[");
		sb.append(getDividend_yield());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eqy_dvd_yld_12m</column-name><column-value><![CDATA[");
		sb.append(getEqy_dvd_yld_12m());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eqy_dvd_yld_es</column-name><column-value><![CDATA[");
		sb.append(getEqy_dvd_yld_es());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dvd_payout_ratio</column-name><column-value><![CDATA[");
		sb.append(getDvd_payout_ratio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pe_ratio</column-name><column-value><![CDATA[");
		sb.append(getPe_ratio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tot_debt_to_com_eqy</column-name><column-value><![CDATA[");
		sb.append(getTot_debt_to_com_eqy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ebitda_to_revenue</column-name><column-value><![CDATA[");
		sb.append(getEbitda_to_revenue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trail_12m_prof_margin</column-name><column-value><![CDATA[");
		sb.append(getTrail_12m_prof_margin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>best_current_ev_best_opp</column-name><column-value><![CDATA[");
		sb.append(getBest_current_ev_best_opp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eqy_beta</column-name><column-value><![CDATA[");
		sb.append(getEqy_beta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>return_sharpe_ratio</column-name><column-value><![CDATA[");
		sb.append(getReturn_sharpe_ratio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eqy_sharpe_ratio_1yr</column-name><column-value><![CDATA[");
		sb.append(getEqy_sharpe_ratio_1yr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eqy_sharpe_ratio_3yr</column-name><column-value><![CDATA[");
		sb.append(getEqy_sharpe_ratio_3yr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eqy_sharpe_ratio_5yr</column-name><column-value><![CDATA[");
		sb.append(getEqy_sharpe_ratio_5yr());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Equity.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Equity.class };
	private long _assetId;
	private double _eqy_alpha;
	private double _dividend_yield;
	private double _eqy_dvd_yld_12m;
	private double _eqy_dvd_yld_es;
	private double _dvd_payout_ratio;
	private double _pe_ratio;
	private double _tot_debt_to_com_eqy;
	private double _ebitda_to_revenue;
	private double _trail_12m_prof_margin;
	private double _best_current_ev_best_opp;
	private double _eqy_beta;
	private double _return_sharpe_ratio;
	private double _eqy_sharpe_ratio_1yr;
	private double _eqy_sharpe_ratio_3yr;
	private double _eqy_sharpe_ratio_5yr;
	private Equity _escapedModel;
}